### ISSUE TITLE
Referenced flatpak dir does not exist

### ISSUE THREAD

**Issue by reinderien** [cra0zy/monodevelop-run-installer#1]
```
$ ./generate.sh 
Copying installer data...
cp: cannot stat '~/.local/share/flatpak/app/com.xamarin.MonoDevelop/current/active/files/lib/monodevelop/.': No such file or directory
Building the Installer...
Header is 401 lines long

About to compress 44 KB of data...
Adding files to archive named "../bin/monodevelop.run"...
./
./mdtool-stable
./postinstall.sh
./monodevelop-stable
./MonoDevelop/
./monodevelop-stable.svg
./monodevelop-stable-uninstall
CRC: 3661661721
MD5: d33a478e34648e2eb9efcfc9c9d785c6

Self-extractible archive "../bin/monodevelop.run" successfully created.
Cleaning Up...
Done :)
```

The produced .run is only 16k, so clearly there are at least two things wrong here:
- The referenced 'app' dir does not exist even though the flatpak is installed:
```
$ ls ~/.local/share/flatpak/
.changed      db/           repo/         system-cache/
```
- There is no error checking to verify that the referenced app folder does in fact exist.

**Comment by harry-cpp** [comment]
> The referenced 'app' dir does not exist even though the flatpak is installed:

It does if you install it with `--user` flag, tho I should also add `/usr/local/share/flatpak` dir as well for searching for the md binaries.

> There is no error checking to verify that the referenced app folder does in fact exist.

I guess I could check for that, might as well add flatpak install and update commands to automate it even more.

**Comment by reinderien** [comment]
OK 😃 Thank you. I will try again using --user.

Could I request that you rework the readme to show, in order, the commands to perform the flatpak install, run your generate, and then run the installer? It would make things much clearer, I think.

**Comment by reinderien** [comment]
After adding --user, it works, no flatpak issues, everything is awesome ❤❤❤

**Comment by harry-cpp** [comment]
Ok. I pushed an update, in short the changes are:
 - It will check if flatpak is installed
 - It will pick up system MD
 - It will install MD from flatpak if it's not installed
 - It will autoupdate MD if it is found

Feel free to try it out.
