### ISSUE TITLE
What's up with Git version control addin?

### ISSUE THREAD

**Issue by roman-yagodin** [cra0zy/monodevelop-run-installer#2]
Great work, @cra0zy! 👍 

I also hope that Git version control addin will make it way to the installer in the one of the nearest releases.

**Comment by harry-cpp** [comment]
The Git addin depends on some outdated libs, and it will cause some crashes to occur so I skipped adding it: https://github.com/cra0zy/monodevelop-run-installer/blob/master/generate.sh#L44

That being said MD 7.1 decided to go in a route that... well.. includes custom? msbuild, newest version of gtk-sharp-2, etc. so I don't think repackaging will be an option for much longer :(

**Comment by roman-yagodin** [comment]
Sad news... I thought Xamarin ship newest versions of msbuild, gtk-sharp-2, etc. using its own Linux repositories!..

**Comment by harry-cpp** [comment]
I have definitely phrased myself badly there, sorry, my thinking was more on these 2 points:
 - only xamarin repos contain the needed newest stuff (so only Ubuntu, Debian and CentOS can really get them installed... even Arch Linux doesn't have some of the stuff...)
 - with what they started they will probably start using some native stuff which some distros don't have

So in short, repackaging is possible right now, it already became a pain to setup on any Linux distro that xamarin does not provide a repo for, and it might become even more problematic down the line.

PS. They are not using custom msbuild, its just that msbuild is split in 2 packages in their repos, didn't notice it before.

**Comment by harry-cpp** [comment]
I've updated the script for the latest MD, and also made some adjustments so that Git Version Control addin can be used.

**Comment by roman-yagodin** [comment]
Thanks! 👍
