### ISSUE TITLE
libgit2 not found

### ISSUE THREAD

**Issue by sbrl** [cra0zy/monodevelop-run-installer#3]
I've just run the latest `.run` installer, and got the following error:

```
libgit2 not found, please install it and re run the installer.
```

 - `uname -a`: `Linux Riikaan 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- OS: Ubuntu 17.04

I've got the `libgit2-24` package installed already - there's no `libgit2` package. I assume there's a `-cil` package I'm missing perhaps?

Either way, it would help if the required packages were documented in the readme.

**Comment by sbrl** [comment]
Thanks a ton! That latest release did the trick :smiley_cat: 

I don't know what I do without this installer :P

**Comment by ghost** [comment]
Hi, this very same issue happened with monodevelop-7.3.3.5-1.run installer.

```sh
uname -a

Linux why 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 i686 i686 GNU/Linux

```

on Ubuntu 16.04.

Also doesn't work with version 7.1.0.1291-2.

Is it because of my 32 bit system (the changes in the postinstall script seems only for x86_64) ?

Thanks.

**Comment by harry-cpp** [comment]
I probably should just parse `ldconfig` output... I'll look into it tomorrow.

**Comment by sbrl** [comment]
@cra0zy I'm not sure what `ldconfig` does, but using `awk` I can obtain the path to `libgit*.so.*` by utilising `awk`:

```bash
ldconfig -p | awk '/^\s+libgit[0-9]+\.so/ { print $4 }'
```

**Comment by harry-cpp** [comment]
The libgit search path has been fixed in master, I also published a new fixed up release build.

**Comment by ghost** [comment]
Thanks! Will retry it again.
