### ISSUE TITLE
Should publish a new release to catch up with MonoDevelop 7.3 release

### ISSUE THREAD

**Issue by lextm** [cra0zy/monodevelop-run-installer#5]
MonoDevelop 7.3 does introduce some important updates (such as VSTest integration), so hope this installer would be updated to have a new release.

**Comment by harry-cpp** [comment]
Sorry it took me so long to respond, the comment slipped by, the new release has been packaged and published: https://github.com/cra0zy/monodevelop-run-installer/releases/tag/7.3.3.5-1

PS. You can always run generate.sh yourself to generate the package.
