### ISSUE TITLE
No dark theme?

### ISSUE THREAD

**Issue by sbrl** [cra0zy/monodevelop-run-installer#6]
Since MonoDevelop 6, there has apparently been a dark interface skin that comes with MonoDevelop. However, when going to Edit -> Preferences -> Visual Style -> User Interface Theme, I can only see the following options:

 - (Default)
 - Ambience
 - High Contrast
 - Radiance
 - Raleigh

....but no dark theme :-(

**Comment by harry-cpp** [comment]
MonoDevelop is now using your system theme, so if your desktop is using a dark theme, it becomes dark.

This is just an unofficial packaging of MonoDevelop as such this issue is unrelated... closing...

**Comment by sbrl** [comment]
.....I see. If I install the flatpak version of MonoDevelop , I do see a dark skin option in the list - so I thought that it would be a packaging issue.

**Comment by harry-cpp** [comment]
> .....I see. If I install the flatpak version of MonoDevelop , I do see a dark skin option in the list - so I thought that it would be a packaging issue.

MonoDevelop is a GTK 2 application, so it can't load a Gtk 3 dark theme. Try something like Arc Dark which also provides a dark theme for GTK 2.

**Comment by sbrl** [comment]
Ok, thanks for the info!
