### ISSUE TITLE
Unable to use External console

### ISSUE THREAD

**Issue by DanteMarshal** [cra0zy/monodevelop-run-installer#7]
Steps to produce :
1. Install Mono Develop using .run package
`Mono Develop 5 provided from repositories works fine, But it's old !`
2. Run `monodevelop-stable`
3. Create a Hello world project and try to Run (on external console) : It won't show Any output !
4. Try to debug the project (Again, on external console) : Could not connect to the debugger

**Solution ?** Uncheck `Run on external console` under Run in Project options.

But, What if I want to Run / Debug my project on external console ?
`By the Way, I'm using Ubuntu Mate 16.04 (Mate desktop as expected).`

**Comment by harry-cpp** [comment]
This issue is unrelated to packaging, as such, closing...

**Comment by DanteMarshal** [comment]
But why does `Mono Develop 5 provided from repositories work fine` ?

**Comment by lextm** [comment]
@Marshal313 The packaged version is MonoDevelop 7. If you do have any question on the bugs/issues, go to MonoDevelop, https://github.com/mono/monodevelop/issues

**Comment by harry-cpp** [comment]
Thank you @lextm
